// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD03vRa_hFVbxwV4MzHIrGWrCNhrX9B7_g',
    appId: '1:722468154656:web:1b6c79e08a62718eeefb45',
    messagingSenderId: '722468154656',
    projectId: 'share-7d60c',
    authDomain: 'share-7d60c.firebaseapp.com',
    storageBucket: 'share-7d60c.appspot.com',
    measurementId: 'G-VNQQ72CVKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQmU824pv03IFSPjEXKpfoxERQ41pXggw',
    appId: '1:722468154656:android:a49ef117276f3379eefb45',
    messagingSenderId: '722468154656',
    projectId: 'share-7d60c',
    storageBucket: 'share-7d60c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG07jaq8PyMSCfLDpL6gwl8jN4XxkfwwM',
    appId: '1:722468154656:ios:ba9886af2accd1c3eefb45',
    messagingSenderId: '722468154656',
    projectId: 'share-7d60c',
    storageBucket: 'share-7d60c.appspot.com',
    iosClientId: '722468154656-1cferl1gho4sv9kddghp1k2iqap32ect.apps.googleusercontent.com',
    iosBundleId: 'com.example.share123',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG07jaq8PyMSCfLDpL6gwl8jN4XxkfwwM',
    appId: '1:722468154656:ios:3f8919aef93d3dffeefb45',
    messagingSenderId: '722468154656',
    projectId: 'share-7d60c',
    storageBucket: 'share-7d60c.appspot.com',
    iosClientId: '722468154656-6urbp4lrn6j06k4uhmfq6ut8pnhe0tof.apps.googleusercontent.com',
    iosBundleId: 'com.example.share',
  );
}
